name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GHACTION_TOKEN }}

  attach-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
          - target: aarch64-apple-darwin
          - target: x86_64-unknown-linux-gnu
          - target: x86_64-apple-darwin

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List available artifacts
        run: gh run list --workflow=build.yml --artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GHACTION_TOKEN }}
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      # - name: Download build artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: pick-${{ matrix.target }}
      - name: Display structure of all downloaded files
        run: ls -R
      - name: Attach artifacts to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHACTION_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./pick-${{ matrix.target }}
          asset_name: pick-${{ matrix.target }}
          asset_content_type: application/octet-stream
